(() => {
  "use strict";

  const Core = window.TextGameCore;
  const ATTRS = ["str","end","vit","mnd","agi","dex","int"];
  const PRESETS = ["optimal_killer","self_preserving","dramatic_gm"];
  const ABILITY_TEMPLATES = {
    "Weak melee": {kind:"attack",ap:1,stamina:0,mana:0,power:30,minRange:0,maxRange:0,attackBonus:25,tags:["Physical"]},
    "Strong melee": {kind:"attack",ap:1,stamina:0,mana:0,power:55,minRange:0,maxRange:0,attackBonus:40,tags:["Physical"]},
    "Weak ranged": {kind:"attack",ap:1,stamina:0,mana:0,power:30,minRange:0,maxRange:1,attackBonus:25,tags:["Physical"]},
    "Strong ranged": {kind:"attack",ap:1,stamina:0,mana:0,power:55,minRange:0,maxRange:2,attackBonus:40,tags:["Physical"]},
    "Weak magic melee": {kind:"attack",ap:1,stamina:0,mana:2,power:35,minRange:0,maxRange:0,attackBonus:30,tags:["Magical"]},
    "Strong magic melee": {kind:"attack",ap:1,stamina:0,mana:2,power:60,minRange:0,maxRange:0,attackBonus:45,tags:["Magical"]},
    "Weak magic ranged": {kind:"attack",ap:1,stamina:0,mana:2,power:35,minRange:0,maxRange:1,attackBonus:30,tags:["Magical"]},
    "Strong magic ranged": {kind:"attack",ap:1,stamina:0,mana:2,power:60,minRange:0,maxRange:2,attackBonus:45,tags:["Magical"]},
    "Multi-target": {kind:"multi",ap:2,stamina:0,mana:0,power:40,minRange:0,maxRange:0,attackBonus:0,minTargets:2,maxTargets:3,tags:["Physical"]},
    "Push attack": {kind:"push",ap:1,stamina:0,mana:0,power:40,minRange:0,maxRange:0,attackBonus:35,tags:["Physical"]},
    "Persistent attack": {kind:"persistent",ap:2,stamina:0,mana:0,power:40,minRange:0,maxRange:0,attackBonus:35,condition:{id:"Persistent Damage",amount:10,expression:"Bleeding"},tags:["Physical"]}
  };

  const $ = s => document.querySelector(s);
  const canvas = $("#canvas"), edgesSvg = $("#edges"), inspector = $("#inspector");
  const fileLabel = $("#fileLabel");
  let adventure = null, selected = null, selectedChoice = null, fileHandle = null;
  let history = [], future = [], dragging = null, battleSceneId = null, battleSelectedZone = null;

  const clone = v => JSON.parse(JSON.stringify(v));
  const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const slug = v => String(v || "item").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"") || "item";
  function unique(base, used){ let id=slug(base), n=2; while(used.has(id)) id=`${slug(base)}-${n++}`; return id; }
  function scenes(){ return adventure?.scenes || {}; }
  function nodePos(id,index=0){ const p=adventure?.editor?.nodes?.[id]; return p || {x:90+(index%4)*290,y:70+Math.floor(index/4)*190}; }
  function ensureEditor(){ adventure.editor ||= {}; adventure.editor.nodes ||= {}; }
  function checkpoint(){ if(!adventure)return; history.push(JSON.stringify(adventure)); if(history.length>100)history.shift(); future=[]; updateUndo(); }
  function mutate(fn){ if(!adventure)return; checkpoint(); fn(); render(); }
  function updateUndo(){ $("#undoBtn").disabled=!history.length; $("#redoBtn").disabled=!future.length; }
  function resetHistory(){ history=[]; future=[]; updateUndo(); }
  function undo(){ if(!history.length||!adventure)return; future.push(JSON.stringify(adventure)); adventure=JSON.parse(history.pop()); selected=null; selectedChoice=null; render(); updateUndo(); }
  function redo(){ if(!future.length||!adventure)return; history.push(JSON.stringify(adventure)); adventure=JSON.parse(future.pop()); selected=null; selectedChoice=null; render(); updateUndo(); }

  function newAdventure(id,title,days){
    adventure={schemaVersion:2,kind:"adventure",id:slug(id),title:title.trim(),startScene:"start",questDays:Number(days)||0,initialState:{flags:{},counters:{}},clocks:{},party:[],scenes:{start:{type:"scene",title:"Opening",text:["Write the opening of the adventure."],choices:[]}},editor:{nodes:{start:{x:120,y:100}}}};
    fileHandle=null; selected="start"; selectedChoice=null; resetHistory(); render();
  }

  function knownTopFields(obj){ return Object.keys(obj).every(k=>["schemaVersion","kind","id","title","startScene","questDays","initialState","clocks","party","scenes","editor"].includes(k)); }
  function assertOpenable(obj){
    if(!obj||obj.kind!=="adventure")throw new Error("This file is not an adventure JSON file.");
    if(obj.schemaVersion!==2)throw new Error(`Adventure schema ${obj.schemaVersion ?? "unknown"} is not supported. The app or adventure schema may be out of date.`);
    if(!knownTopFields(obj))throw new Error("This adventure contains structural fields this version of Adventure Author does not understand. The app or adventure schema may be out of date.");
    if(!obj.scenes||typeof obj.scenes!=="object")throw new Error("Adventure scenes are missing.");
  }
  function normalizeLayout(){ ensureEditor(); let i=0; for(const id of Object.keys(scenes())) if(!adventure.editor.nodes[id])adventure.editor.nodes[id]=nodePos(id,i++); }

  async function openFile(){
    try{
      if(window.showOpenFilePicker){
        const [h]=await window.showOpenFilePicker({types:[{description:"Adventure JSON",accept:{"application/json":[".json"]}}],multiple:false});
        const f=await h.getFile(), obj=JSON.parse(await f.text()); assertOpenable(obj); adventure=obj; fileHandle=h; normalizeLayout(); selected=null; selectedChoice=null; resetHistory(); render(); return;
      }
    }catch(e){ if(e.name==="AbortError")return; alert(e.message); return; }
    $("#fallbackOpen").click();
  }
  $("#fallbackOpen").addEventListener("change",async e=>{ const f=e.target.files[0]; if(!f)return; try{const obj=JSON.parse(await f.text());assertOpenable(obj);adventure=obj;fileHandle=null;normalizeLayout();selected=null;selectedChoice=null;resetHistory();render();}catch(err){alert(err.message)} e.target.value=""; });
  async function saveFile(){
    if(!adventure)return; const text=JSON.stringify(adventure,null,2)+"\n";
    if(fileHandle){ try{const w=await fileHandle.createWritable();await w.write(text);await w.close();fileLabel.textContent=`${adventure.id}.json`;return;}catch(e){alert(`Could not overwrite the file: ${e.message}`);return;} }
    try{
      if(window.showSaveFilePicker){fileHandle=await window.showSaveFilePicker({suggestedName:`${adventure.id}.json`,types:[{description:"Adventure JSON",accept:{"application/json":[".json"]}}]});const w=await fileHandle.createWritable();await w.write(text);await w.close();fileLabel.textContent=`${adventure.id}.json`;return;}
    }catch(e){if(e.name==="AbortError")return;}
    const blob=new Blob([text],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${adventure.id}.json`;a.click();URL.revokeObjectURL(a.href);alert("This browser cannot overwrite the original file directly. A new JSON file was downloaded instead.");
  }

  function outputsFor(scene){
    const out=[];
    if(scene.type==="scene") for(const c of scene.choices||[]){ if(c.resolution==="automatic")out.push({label:c.label||c.id,next:c.outcome?.next}); else if(c.resolution==="check"){out.push({label:`${c.label}: success`,next:c.success?.next});out.push({label:`${c.label}: failure`,next:c.failure?.next});out.push({label:`${c.label}: twist`,next:c.twist?.next});} }
    if(scene.type==="combat"){out.push({label:"Victory",next:scene.victory?.next});out.push({label:"Defeat",next:scene.defeat?.next});}
    return out;
  }
  function renderGraph(){
    canvas.innerHTML=""; edgesSvg.innerHTML=""; if(!adventure)return;
    const ids=Object.keys(scenes()); normalizeLayout();
    ids.forEach((id,i)=>{const s=scenes()[id],p=nodePos(id,i),el=document.createElement("div");el.className=`node ${s.type}${selected===id?" selected":""}`;el.dataset.id=id;el.style.left=`${p.x}px`;el.style.top=`${p.y}px`;const ports=outputsFor(s).map(o=>`<span class="port">${esc(o.label)}</span>`).join("");el.innerHTML=`<div class="node-head"><span>${esc(s.title||id)}</span><span class="node-id">${esc(id)}</span></div><div class="node-body">${s.type==="scene"?`${(s.text||[]).length} passages · ${(s.choices||[]).length} choices`:s.type==="combat"?`${(s.enemies||[]).length} enemies · ${(s.battlefield?.zones||[]).length} zones`:esc(s.outcome||"ending")}<div class="port-row">${ports}</div></div>`;el.addEventListener("mousedown",startDrag);el.addEventListener("click",e=>{e.stopPropagation();selected=id;selectedChoice=null;render();});canvas.appendChild(el);});
    requestAnimationFrame(renderEdges);
  }
  function renderEdges(){ edgesSvg.innerHTML=""; if(!adventure)return; for(const [from,s] of Object.entries(scenes())){const a=document.querySelector(`.node[data-id="${CSS.escape(from)}"]`);if(!a)continue;for(const o of outputsFor(s)){if(!o.next)continue;const b=document.querySelector(`.node[data-id="${CSS.escape(o.next)}"]`);if(!b)continue;const x1=a.offsetLeft+a.offsetWidth,y1=a.offsetTop+a.offsetHeight/2,x2=b.offsetLeft,y2=b.offsetTop+b.offsetHeight/2,c=Math.max(60,Math.abs(x2-x1)*.45);const path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("class","edge");path.setAttribute("d",`M${x1},${y1} C${x1+c},${y1} ${x2-c},${y2} ${x2},${y2}`);edgesSvg.appendChild(path);}}
  }
  function startDrag(e){ if(e.button!==0)return; const id=e.currentTarget.dataset.id,p=nodePos(id),sx=e.clientX,sy=e.clientY;dragging={id,sx,sy,x:p.x,y:p.y,moved:false};document.addEventListener("mousemove",dragMove);document.addEventListener("mouseup",dragEnd,{once:true}); }
  function dragMove(e){if(!dragging)return;const dx=e.clientX-dragging.sx,dy=e.clientY-dragging.sy;if(Math.abs(dx)+Math.abs(dy)>3)dragging.moved=true;ensureEditor();adventure.editor.nodes[dragging.id]={x:Math.max(0,dragging.x+dx),y:Math.max(0,dragging.y+dy)};const el=document.querySelector(`.node[data-id="${CSS.escape(dragging.id)}"]`);if(el){el.style.left=`${adventure.editor.nodes[dragging.id].x}px`;el.style.top=`${adventure.editor.nodes[dragging.id].y}px`;renderEdges();}}
  function dragEnd(){document.removeEventListener("mousemove",dragMove);if(dragging?.moved){history.push(JSON.stringify({...adventure,editor:{...adventure.editor,nodes:{...adventure.editor.nodes,[dragging.id]:{x:dragging.x,y:dragging.y}}}}));future=[];updateUndo();}dragging=null;}

  function optionsScenes(current=""){return `<option value="">— end/unwired —</option>`+Object.entries(scenes()).map(([id,s])=>`<option value="${esc(id)}" ${id===current?"selected":""}>${esc(id)} · ${esc(s.title)}</option>`).join("");}
  function field(label,value,key,type="text"){return `<label class="field"><span>${esc(label)}</span><input data-field="${esc(key)}" type="${type}" value="${esc(value)}"></label>`;}
  function bindFields(root,obj,onChange=()=>{}){ root.querySelectorAll("[data-field]").forEach(el=>el.addEventListener("change",()=>mutate(()=>{let v=el.type==="number"?Number(el.value):el.value;obj[el.dataset.field]=v;onChange();}))); }
  function effectEditor(effects=[]){const paths=statePaths();return `<div class="stack">${effects.map((ef,i)=>`<div class="card"><div class="row three"><select data-effect-type="${i}"><option ${ef.type==="set"?"selected":""}>set</option><option ${ef.type==="add"?"selected":""}>add</option><option value="advance-clock" ${ef.type==="advance-clock"?"selected":""}>advance-clock</option></select>${ef.type==="advance-clock"?`<select data-effect-clock="${i}">${Object.keys(adventure.clocks||{}).map(id=>`<option ${ef.id===id?"selected":""}>${esc(id)}</option>`)}</select><input data-effect-value="${i}" type="number" value="${esc(ef.segments??1)}">`:`<select data-effect-path="${i}">${paths.map(p=>`<option ${ef.path===p?"selected":""}>${esc(p)}</option>`)}</select><input data-effect-value="${i}" value="${esc(ef.value ?? "")}">`}</div><button class="mini-btn danger" data-remove-effect="${i}">Remove</button></div>`).join("")}<button class="mini-btn" data-add-effect>Add effect</button></div>`;}
  function statePaths(){return ["quest.elapsedDays",...Object.keys(adventure.initialState?.flags||{}).map(k=>`flags.${k}`),...Object.keys(adventure.initialState?.counters||{}).map(k=>`counters.${k}`)];}
  function bindEffects(root,outcome){ outcome.effects ||= []; root.querySelector("[data-add-effect]")?.addEventListener("click",()=>mutate(()=>outcome.effects.push({type:"set",path:statePaths()[0]||"quest.elapsedDays",value:true})));root.querySelectorAll("[data-remove-effect]").forEach(b=>b.onclick=()=>mutate(()=>outcome.effects.splice(Number(b.dataset.removeEffect),1)));root.querySelectorAll("[data-effect-type]").forEach(el=>el.onchange=()=>mutate(()=>{const i=Number(el.dataset.effectType);outcome.effects[i]=el.value==="advance-clock"?{type:"advance-clock",id:Object.keys(adventure.clocks||{})[0]||"clock",segments:1}:{type:el.value,path:statePaths()[0]||"quest.elapsedDays",value:el.value==="add"?1:true};}));root.querySelectorAll("[data-effect-path]").forEach(el=>el.onchange=()=>mutate(()=>outcome.effects[Number(el.dataset.effectPath)].path=el.value));root.querySelectorAll("[data-effect-clock]").forEach(el=>el.onchange=()=>mutate(()=>outcome.effects[Number(el.dataset.effectClock)].id=el.value));root.querySelectorAll("[data-effect-value]").forEach(el=>el.onchange=()=>mutate(()=>{const ef=outcome.effects[Number(el.dataset.effectValue)],raw=el.value;const val=raw==="true"?true:raw==="false"?false:(raw!==""&&!Number.isNaN(Number(raw))?Number(raw):raw);if(ef.type==="advance-clock")ef.segments=Number(raw)||0;else ef.value=val;})); }
  function outcomeEditor(name,outcome){return `<div class="section"><h3>${esc(name)}</h3><label class="field"><span>Text</span><textarea data-outcome-text>${esc(outcome.text||"")}</textarea></label><label class="field"><span>Destination</span><select data-outcome-next>${optionsScenes(outcome.next||"")}</select></label><h4>Effects</h4>${effectEditor(outcome.effects||[])}</div>`;}
  function bindOutcome(root,outcome){root.querySelector("[data-outcome-text]").onchange=e=>mutate(()=>outcome.text=e.target.value);root.querySelector("[data-outcome-next]").onchange=e=>mutate(()=>{if(e.target.value)outcome.next=e.target.value;else delete outcome.next;delete outcome.end;});bindEffects(root,outcome);}

  function renderSceneInspector(id,s){
    if(selectedChoice!=null)return renderChoiceInspector(id,s,selectedChoice);
    inspector.innerHTML=`<h2>Scene</h2>${field("ID",id,"__id")}${field("Title",s.title,"title")}<div class="section"><div class="section-title"><h3>Passages</h3><div><button class="mini-btn" id="addNarration">+ Narration</button> <button class="mini-btn" id="addDialogue">+ Dialogue</button></div></div><div class="stack">${(s.text||[]).map((p,i)=>typeof p==="string"?`<div class="card"><div class="card-title"><span>Narration</span><span><button data-up-pass="${i}">↑</button><button data-down-pass="${i}">↓</button><button data-del-pass="${i}">×</button></span></div><textarea data-pass-text="${i}">${esc(p)}</textarea></div>`:`<div class="card"><div class="card-title"><span>Dialogue</span><span><button data-up-pass="${i}">↑</button><button data-down-pass="${i}">↓</button><button data-del-pass="${i}">×</button></span></div><input data-pass-speaker="${i}" value="${esc(p.speaker)}" placeholder="Speaker"><textarea data-pass-text="${i}">${esc(p.text)}</textarea></div>`).join("")}</div></div><div class="section"><div class="section-title"><h3>Choices</h3><div><button class="mini-btn" id="addAutomatic">+ Automatic</button> <button class="mini-btn" id="addCheck">+ Check</button></div></div><div class="stack">${(s.choices||[]).map((c,i)=>`<button data-choice="${i}">${esc(c.label||c.id)} <span class="badge">${esc(c.resolution)}</span></button>`).join("")||'<span class="muted">No choices yet.</span>'}</div></div><button class="danger" id="deleteNode">Delete scene</button>`;
    inspector.querySelector('[data-field="title"]').onchange=e=>mutate(()=>s.title=e.target.value);
    inspector.querySelector('[data-field="__id"]').onchange=e=>renameScene(id,e.target.value);
    $("#addNarration").onclick=()=>mutate(()=>{s.text ||= [];s.text.push("New narration.")});$("#addDialogue").onclick=()=>mutate(()=>{s.text ||= [];s.text.push({speaker:"Speaker",text:"New dialogue."})});
    inspector.querySelectorAll("[data-pass-text]").forEach(el=>el.onchange=()=>mutate(()=>{const i=Number(el.dataset.passText);if(typeof s.text[i]==="string")s.text[i]=el.value;else s.text[i].text=el.value;}));inspector.querySelectorAll("[data-pass-speaker]").forEach(el=>el.onchange=()=>mutate(()=>s.text[Number(el.dataset.passSpeaker)].speaker=el.value));
    inspector.querySelectorAll("[data-del-pass]").forEach(b=>b.onclick=()=>mutate(()=>s.text.splice(Number(b.dataset.delPass),1)));inspector.querySelectorAll("[data-up-pass]").forEach(b=>b.onclick=()=>mutate(()=>moveItem(s.text,Number(b.dataset.upPass),-1)));inspector.querySelectorAll("[data-down-pass]").forEach(b=>b.onclick=()=>mutate(()=>moveItem(s.text,Number(b.dataset.downPass),1)));
    inspector.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{selectedChoice=Number(b.dataset.choice);renderInspector();});
    $("#addAutomatic").onclick=()=>mutate(()=>{s.choices ||= [];const uid=unique("choice",new Set(s.choices.map(x=>x.id)));s.choices.push({id:uid,label:"New choice",resolution:"automatic",reason:"No roll is required.",outcome:{text:"Describe what happens.",next:""}});selectedChoice=s.choices.length-1;});
    $("#addCheck").onclick=()=>mutate(()=>{s.choices ||= [];const uid=unique("check",new Set(s.choices.map(x=>x.id)));s.choices.push({id:uid,label:"Attempt a challenge",resolution:"check",actor:{mode:"select",eligible:["*"]},check:{goal:"State the goal.",approach:"State the approach.",baseTN:40,attributes:["int","dex"],skill:"Awareness",situationalModifiers:[]},success:{text:"The goal succeeds.",next:""},failure:{text:"The goal fails and the situation changes.",next:""},twistPreview:"The goal succeeds, but there is a complication.",twist:{text:"The goal succeeds with a complication.",next:""}});selectedChoice=s.choices.length-1;});
    $("#deleteNode").onclick=()=>deleteNode(id);
  }
  function moveItem(a,i,d){const j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];}

  function whenEditor(when){ const conds=when?.all||[]; return `<div class="section"><div class="section-title"><h3>Visibility</h3><button class="mini-btn" data-add-condition>+ Condition</button></div>${conds.map((c,i)=>`<div class="row three"><select data-cond-path="${i}">${statePaths().map(p=>`<option ${c.path===p?"selected":""}>${esc(p)}</option>`)}</select><select data-cond-op="${i}">${["equals","notEquals","gte","lte"].map(op=>`<option ${c[op]!==undefined?"selected":""}>${op}</option>`)}</select><input data-cond-val="${i}" value="${esc(c.equals??c.notEquals??c.gte??c.lte??"")}"></div><button class="mini-btn danger" data-del-condition="${i}">Remove</button>`).join("")||'<p class="hint">Always visible.</p>'}</div>`; }
  function bindWhen(root,c){root.querySelector("[data-add-condition]").onclick=()=>mutate(()=>{c.when ||= {all:[]};c.when.all ||= [];c.when.all.push({path:statePaths()[0]||"quest.elapsedDays",equals:true});});root.querySelectorAll("[data-del-condition]").forEach(b=>b.onclick=()=>mutate(()=>{c.when.all.splice(Number(b.dataset.delCondition),1);if(!c.when.all.length)delete c.when;}));root.querySelectorAll("[data-cond-path]").forEach(el=>el.onchange=()=>mutate(()=>c.when.all[Number(el.dataset.condPath)].path=el.value));root.querySelectorAll("[data-cond-op]").forEach(el=>el.onchange=()=>mutate(()=>{const x=c.when.all[Number(el.dataset.condOp)],v=x.equals??x.notEquals??x.gte??x.lte;for(const k of ["equals","notEquals","gte","lte"])delete x[k];x[el.value]=v;}));root.querySelectorAll("[data-cond-val]").forEach(el=>el.onchange=()=>mutate(()=>{const x=c.when.all[Number(el.dataset.condVal)],op=["equals","notEquals","gte","lte"].find(k=>x[k]!==undefined),r=el.value;x[op]=r==="true"?true:r==="false"?false:(r!==""&&!Number.isNaN(Number(r))?Number(r):r);}));}
  function renderChoiceInspector(id,s,i){const c=s.choices[i];if(!c){selectedChoice=null;return renderSceneInspector(id,s)}let body=`<button id="backChoice">← Scene</button><h2>Choice</h2>${field("ID",c.id,"id")}${field("Label",c.label,"label")}<label class="field"><span>Description</span><textarea data-choice-desc>${esc(c.description||"")}</textarea></label>${whenEditor(c.when)}`;
    if(c.resolution==="automatic")body+=`${field("Reason",c.reason||"","reason")}${outcomeEditor("Outcome",c.outcome)}`;
    else body+=`<div class="section"><h3>Check</h3><label class="field"><span>Actor mode</span><select id="actorMode"><option value="select" ${c.actor?.mode==="select"?"selected":""}>Selectable</option><option value="fixed" ${c.actor?.mode==="fixed"?"selected":""}>Fixed</option></select></label>${c.actor?.mode==="fixed"?`<label class="field"><span>Actor</span><select id="fixedActor"><option value="$main">$main</option>${(adventure.party||[]).map(p=>`<option value="${esc(p.id)}" ${c.actor.id===p.id?"selected":""}>${esc(p.name)}</option>`)}</select></label>`:`<p class="hint">Selectable actors currently use the whole party (*).</p>`}${field("Goal",c.check.goal||"","goal")}${field("Approach",c.check.approach||"","approach")}${field("Base TN",c.check.baseTN,"baseTN","number")}<div class="row"><label class="field"><span>Attribute 1</span><select id="attr1">${ATTRS.map(a=>`<option ${c.check.attributes?.[0]===a?"selected":""}>${a}</option>`)}</select></label><label class="field"><span>Attribute 2</span><select id="attr2">${ATTRS.map(a=>`<option ${c.check.attributes?.[1]===a?"selected":""}>${a}</option>`)}</select></label></div>${field("Skill",c.check.skill||"","skill")}<label class="field"><span>Clock</span><select id="checkClock"><option value="">None</option>${Object.keys(adventure.clocks||{}).map(k=>`<option ${c.check.clock===k?"selected":""}>${esc(k)}</option>`)}</select></label></div>${outcomeEditor("Success",c.success)}${outcomeEditor("Failure",c.failure)}${field("Twist preview",c.twistPreview||"","twistPreview")}${outcomeEditor("Twist",c.twist)}`;
    body+=`<button class="danger" id="deleteChoice">Delete choice</button>`; inspector.innerHTML=body;$("#backChoice").onclick=()=>{selectedChoice=null;renderInspector()};inspector.querySelector('[data-field="id"]').onchange=e=>mutate(()=>c.id=slug(e.target.value));inspector.querySelector('[data-field="label"]').onchange=e=>mutate(()=>c.label=e.target.value);inspector.querySelector('[data-choice-desc]').onchange=e=>mutate(()=>c.description=e.target.value);bindWhen(inspector,c);
    if(c.resolution==="automatic"){inspector.querySelector('[data-field="reason"]').onchange=e=>mutate(()=>c.reason=e.target.value);bindOutcome(inspector.querySelectorAll(".section")[1],c.outcome);}else{
      $("#actorMode").onchange=e=>mutate(()=>c.actor=e.target.value==="fixed"?{mode:"fixed",id:"$main"}:{mode:"select",eligible:["*"]});$("#fixedActor")&&($("#fixedActor").onchange=e=>mutate(()=>c.actor.id=e.target.value));for(const k of ["goal","approach","baseTN","skill"])inspector.querySelector(`[data-field="${k}"]`).onchange=e=>mutate(()=>c.check[k]=k==="baseTN"?Number(e.target.value):e.target.value);$("#attr1").onchange=e=>mutate(()=>c.check.attributes[0]=e.target.value);$("#attr2").onchange=e=>mutate(()=>c.check.attributes[1]=e.target.value);$("#checkClock").onchange=e=>mutate(()=>{if(e.target.value)c.check.clock=e.target.value;else delete c.check.clock;});inspector.querySelector('[data-field="twistPreview"]').onchange=e=>mutate(()=>c.twistPreview=e.target.value);const outs=inspector.querySelectorAll(".section");bindOutcome(outs[2],c.success);bindOutcome(outs[3],c.failure);bindOutcome(outs[4],c.twist);
    }$("#deleteChoice").onclick=()=>mutate(()=>{s.choices.splice(i,1);selectedChoice=null;});
  }

  function renderCombatInspector(id,s){s.battlefield ||= {zones:[],links:[]};s.pcStarts ||= {};s.enemies ||= [];s.victory ||= {text:"Victory.",next:""};s.defeat ||= {text:"Defeat.",next:""};inspector.innerHTML=`<h2>Combat</h2>${field("ID",id,"__id")}${field("Title",s.title,"title")}<label class="field"><span>Ambush</span><select id="ambush"><option value="false" ${!s.ambush?"selected":""}>No</option><option value="true" ${s.ambush?"selected":""}>Yes</option></select></label><button id="editBattlefield">Edit Battlefield</button>${outcomeEditor("Victory",s.victory)}${outcomeEditor("Defeat",s.defeat)}<button class="danger" id="deleteNode">Delete combat</button>`;inspector.querySelector('[data-field="title"]').onchange=e=>mutate(()=>s.title=e.target.value);inspector.querySelector('[data-field="__id"]').onchange=e=>renameScene(id,e.target.value);$("#ambush").onchange=e=>mutate(()=>s.ambush=e.target.value==="true");$("#editBattlefield").onclick=()=>openBattlefield(id);const sec=inspector.querySelectorAll(".section");bindOutcome(sec[0],s.victory);bindOutcome(sec[1],s.defeat);$("#deleteNode").onclick=()=>deleteNode(id);}
  function renderEndingInspector(id,s){inspector.innerHTML=`<h2>Ending</h2>${field("ID",id,"__id")}${field("Title",s.title,"title")}<label class="field"><span>Outcome</span><select id="endingOutcome"><option ${s.outcome==="victory"?"selected":""}>victory</option><option ${s.outcome==="defeat"?"selected":""}>defeat</option></select></label><label class="field"><span>Text</span><textarea id="endingText">${esc(s.text||"")}</textarea></label><button class="danger" id="deleteNode">Delete ending</button>`;inspector.querySelector('[data-field="title"]').onchange=e=>mutate(()=>s.title=e.target.value);inspector.querySelector('[data-field="__id"]').onchange=e=>renameScene(id,e.target.value);$("#endingOutcome").onchange=e=>mutate(()=>s.outcome=e.target.value);$("#endingText").onchange=e=>mutate(()=>s.text=e.target.value);$("#deleteNode").onclick=()=>deleteNode(id);}
  function renderInspector(){if(!adventure){inspector.innerHTML='<div class="empty-state">Create or open an adventure.</div>';return}if(!selected||!scenes()[selected]){renderMeta();return}const s=scenes()[selected];if(s.type==="scene")renderSceneInspector(selected,s);if(s.type==="combat")renderCombatInspector(selected,s);if(s.type==="ending")renderEndingInspector(selected,s);}

  function renameScene(oldId,newRaw){const id=slug(newRaw);if(id===oldId)return;if(scenes()[id]){alert("That scene id already exists.");renderInspector();return}mutate(()=>{scenes()[id]=scenes()[oldId];delete scenes()[oldId];if(adventure.startScene===oldId)adventure.startScene=id;ensureEditor();adventure.editor.nodes[id]=adventure.editor.nodes[oldId];delete adventure.editor.nodes[oldId];for(const s of Object.values(scenes())){for(const o of outputsForObjects(s))if(o.next===oldId)o.next=id;}selected=id;});}
  function outputsForObjects(s){const a=[];if(s.type==="scene")for(const c of s.choices||[])a.push(...(c.resolution==="automatic"?[c.outcome]:[c.success,c.failure,c.twist]));if(s.type==="combat")a.push(s.victory,s.defeat);return a.filter(Boolean);}
  function deleteNode(id){if(!confirm(`Delete ${id}?`))return;mutate(()=>{delete scenes()[id];delete adventure.editor?.nodes?.[id];for(const s of Object.values(scenes()))for(const o of outputsForObjects(s))if(o.next===id)delete o.next;if(adventure.startScene===id)adventure.startScene=Object.keys(scenes())[0]||"";selected=null;selectedChoice=null;});}

  function renderMeta(){inspector.innerHTML=`<h2>Adventure</h2>${field("Adventure ID",adventure.id,"id")}${field("Title",adventure.title,"title")}${field("Quest days",adventure.questDays??0,"questDays","number")}<label class="field"><span>Start scene</span><select id="startScene">${Object.keys(scenes()).map(id=>`<option ${adventure.startScene===id?"selected":""}>${esc(id)}</option>`)}</select></label><div class="section"><div class="section-title"><h3>Required companions</h3><button id="importCompanion" class="mini-btn">Import character JSON</button></div><div class="stack">${(adventure.party||[]).map((p,i)=>`<div class="card"><strong>${esc(p.name)}</strong><div class="muted">${esc(p.id)} · ${esc(p.role)}</div><button data-remove-party="${i}" class="mini-btn danger">Remove</button></div>`).join("")||'<p class="hint">No required companions. $main is still selected by the player.</p>'}</div></div><p class="hint">Imported companions are copied into this adventure. Players do not need the original character file.</p>`;bindFields(inspector,adventure);$("#startScene").onchange=e=>mutate(()=>adventure.startScene=e.target.value);$("#importCompanion").onclick=importCompanion;inspector.querySelectorAll("[data-remove-party]").forEach(b=>b.onclick=()=>mutate(()=>adventure.party.splice(Number(b.dataset.removeParty),1)));}
  async function importCompanion(){let obj;try{if(window.showOpenFilePicker){const [h]=await window.showOpenFilePicker({types:[{description:"Character JSON",accept:{"application/json":[".json"]}}]});obj=JSON.parse(await (await h.getFile()).text());}else{alert("Use a browser with the File System Access API to import a companion in this version.");return;}const errs=Core?.validateCharacter?Core.validateCharacter(obj):[];if(errs.length)throw new Error(errs.join("\n"));if((adventure.party||[]).some(p=>p.id===obj.id))throw new Error(`Companion id ${obj.id} is already embedded.`);mutate(()=>adventure.party.push(clone(obj)));}catch(e){if(e.name!=="AbortError")alert(e.message);}}

  function renderState(){adventure.initialState ||= {flags:{},counters:{}};adventure.initialState.flags ||= {};adventure.initialState.counters ||= {};adventure.clocks ||= {};const entries=(obj,type)=>Object.entries(obj).map(([k,v])=>`<div class="row"><input data-state-key="${type}:${esc(k)}" value="${esc(k)}"><input data-state-val="${type}:${esc(k)}" value="${esc(v)}"></div>`).join("");inspector.innerHTML=`<h2>State & Clocks</h2><div class="section"><div class="section-title"><h3>Flags</h3><button class="mini-btn" id="addFlag">+ Flag</button></div>${entries(adventure.initialState.flags,"flag")}</div><div class="section"><div class="section-title"><h3>Counters</h3><button class="mini-btn" id="addCounter">+ Counter</button></div>${entries(adventure.initialState.counters,"counter")}</div><div class="section"><div class="section-title"><h3>Clocks</h3><button class="mini-btn" id="addClock">+ Clock</button></div>${Object.entries(adventure.clocks).map(([id,c])=>`<div class="card"><input data-clock-id="${esc(id)}" value="${esc(id)}"><input data-clock-label="${esc(id)}" value="${esc(c.label)}"><select data-clock-size="${esc(id)}">${[2,4,6].map(n=>`<option ${c.size===n?"selected":""}>${n}</option>`)}</select></div>`).join("")}</div><p class="hint">quest.elapsedDays is always available to effects and conditions.</p>`;$("#addFlag").onclick=()=>mutate(()=>adventure.initialState.flags[unique("flag",new Set(Object.keys(adventure.initialState.flags)))]=false);$("#addCounter").onclick=()=>mutate(()=>adventure.initialState.counters[unique("counter",new Set(Object.keys(adventure.initialState.counters)))]=0);$("#addClock").onclick=()=>mutate(()=>adventure.clocks[unique("clock",new Set(Object.keys(adventure.clocks))) ]={label:"Progress",size:4});inspector.querySelectorAll("[data-state-val]").forEach(el=>el.onchange=()=>mutate(()=>{const [t,k]=el.dataset.stateVal.split(":"),raw=el.value,v=raw==="true"?true:raw==="false"?false:(!Number.isNaN(Number(raw))?Number(raw):raw);(t==="flag"?adventure.initialState.flags:adventure.initialState.counters)[k]=v;}));inspector.querySelectorAll("[data-state-key]").forEach(el=>el.onchange=()=>{const [t,k]=el.dataset.stateKey.split(":"),obj=t==="flag"?adventure.initialState.flags:adventure.initialState.counters,n=slug(el.value);if(obj[n]!==undefined&&n!==k){alert("That state key already exists.");renderState();return}mutate(()=>{obj[n]=obj[k];delete obj[k]});});inspector.querySelectorAll("[data-clock-label]").forEach(el=>el.onchange=()=>mutate(()=>adventure.clocks[el.dataset.clockLabel].label=el.value));inspector.querySelectorAll("[data-clock-size]").forEach(el=>el.onchange=()=>mutate(()=>adventure.clocks[el.dataset.clockSize].size=Number(el.value)));}

  function authorIssues(){if(!adventure)return[];const issues=[];for(const e of Core?.validateAdventure?.(adventure)||[])issues.push({level:"error",text:e});const combatIds=Object.entries(scenes()).filter(([,s])=>s.type==="combat").map(([id])=>id);if(combatIds.length>1)issues.push({level:"warning",text:`Adventure contains ${combatIds.length} combats. The game is designed around one substantial combat per adventure.`});if(combatIds.length===0)issues.push({level:"warning",text:"Adventure contains no combat scene."});const endings=Object.entries(scenes()).filter(([,s])=>s.type==="ending").map(([id])=>id);if(!endings.length)issues.push({level:"warning",text:"Adventure contains no ending nodes."});const incoming=new Map(Object.keys(scenes()).map(id=>[id,0]));for(const s of Object.values(scenes()))for(const o of outputsForObjects(s))if(o.next&&incoming.has(o.next))incoming.set(o.next,incoming.get(o.next)+1);for(const [id,n] of incoming)if(id!==adventure.startScene&&n===0)issues.push({level:"info",text:`${id} has no incoming connections.`});const reachable=new Set(),walk=id=>{if(!id||reachable.has(id)||!scenes()[id])return;reachable.add(id);for(const o of outputsForObjects(scenes()[id]))walk(o.next)};walk(adventure.startScene);for(const id of Object.keys(scenes()))if(!reachable.has(id))issues.push({level:"info",text:`${id} is unreachable from the start scene.`});for(const cid of combatIds){const seen=new Set();const dfs=id=>{if(!id||seen.has(id)||!scenes()[id])return false;if(id===cid&&seen.size)return true;seen.add(id);for(const o of outputsForObjects(scenes()[id]))if(dfs(o.next))return true;return false};for(const o of outputsForObjects(scenes()[cid])){seen.clear();if(dfs(o.next)){issues.push({level:"error",text:`Combat ${cid} can loop back into itself. Combat loops are not supported by the authoring model.`});break;}}}return issues;}
  function renderValidation(){const issues=authorIssues();inspector.innerHTML=`<h2>Validation</h2>${["error","warning","info"].map(level=>`<div class="section"><h3 class="${level}">${level[0].toUpperCase()+level.slice(1)}s</h3>${issues.filter(x=>x.level===level).map(x=>`<div class="validation-item ${level}">${esc(x.text)}</div>`).join("")||'<div class="muted">None.</div>'}</div>`).join("")}<p class="hint">Validation never blocks Save.</p>`;}

  function addNode(type){if(!adventure)return;mutate(()=>{const used=new Set(Object.keys(scenes())),id=unique(type,used),index=used.size;if(type==="scene")scenes()[id]={type:"scene",title:"New Scene",text:["New narration."],choices:[]};if(type==="combat")scenes()[id]={type:"combat",title:"New Combat",ambush:false,battlefield:{zones:[{id:"zone-1",name:"Zone 1"}],links:[]},pcStarts:{"$main":"zone-1"},enemies:[],interactions:[],victory:{text:"The party wins.",next:""},defeat:{text:"The party is defeated.",next:""}};if(type==="ending")scenes()[id]={type:"ending",title:"Ending",outcome:"victory",text:"Write the ending."};ensureEditor();adventure.editor.nodes[id]={x:100+(index%4)*280,y:90+Math.floor(index/4)*180};selected=id;selectedChoice=null;});}

  function openBattlefield(id){battleSceneId=id;battleSelectedZone=null;renderBattlefield();$("#battlefieldDialog").showModal();}
  function renderBattlefield(){const s=scenes()[battleSceneId],bc=$("#battleCanvas"),be=$("#battleEdges");bc.innerHTML="";be.innerHTML="";$("#battlefieldTitle").textContent=s.title;s.editor ||= {};s.editor.zones ||= {};const zones=s.battlefield.zones||[];zones.forEach((z,i)=>{const p=s.editor.zones[z.id]||{x:70+(i%4)*240,y:60+Math.floor(i/4)*180};s.editor.zones[z.id]=p;const pcs=Object.entries(s.pcStarts||{}).filter(([,zone])=>zone===z.id).map(([id])=>`<span class="chip">${esc(id)}</span>`).join("");const enemies=(s.enemies||[]).filter(e=>e.zone===z.id).map(e=>`<span class="chip enemy">${esc(e.name)}</span>`).join("");const el=document.createElement("div");el.className=`node zone-node${battleSelectedZone===z.id?" selected":""}`;el.style.left=`${p.x}px`;el.style.top=`${p.y}px`;el.innerHTML=`<div class="node-head"><span>${esc(z.name)}</span><span class="node-id">${esc(z.id)}</span></div><div class="node-body">${pcs}${enemies}</div>`;el.onclick=()=>{battleSelectedZone=z.id;renderBattlefield()};bc.appendChild(el);});requestAnimationFrame(()=>{for(const l of s.battlefield.links||[]){const za=zones.findIndex(z=>z.id===l.from),zb=zones.findIndex(z=>z.id===l.to);if(za<0||zb<0)continue;const pa=s.editor.zones[l.from],pb=s.editor.zones[l.to],x1=pa.x+180,y1=pa.y+50,x2=pb.x,y2=pb.y+50,path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("class","edge");path.setAttribute("d",`M${x1},${y1} C${x1+70},${y1} ${x2-70},${y2} ${x2},${y2}`);be.appendChild(path);}});renderBattleInspector();}
  function renderBattleInspector(){const s=scenes()[battleSceneId],bi=$("#battleInspector");if(battleSelectedZone){const z=s.battlefield.zones.find(x=>x.id===battleSelectedZone);bi.innerHTML=`<h3>Zone</h3>${field("ID",z.id,"id")}${field("Name",z.name,"name")}<button id="addLink" class="mini-btn">Connect to zone…</button><h3>PC starts</h3>${["$main",...(adventure.party||[]).map(p=>p.id)].map(id=>`<label class="field"><span>${esc(id)}</span><select data-pc-start="${esc(id)}">${s.battlefield.zones.map(q=>`<option value="${esc(q.id)}" ${s.pcStarts?.[id]===q.id?"selected":""}>${esc(q.name)}</option>`)}</select></label>`).join("")}<h3>Enemies here</h3>${(s.enemies||[]).filter(e=>e.zone===z.id).map((e,i)=>`<button data-edit-enemy="${esc(e.id)}">${esc(e.name)}</button>`).join(" ")}<button id="addEnemy" class="mini-btn">+ Enemy</button><h3>Interactions</h3>${(s.interactions||[]).filter(x=>x.zone===z.id).map(x=>`<div class="card">${esc(x.name)}</div>`).join("")}<button id="addInteraction" class="mini-btn">+ Interaction</button>`;bi.querySelector('[data-field="name"]').onchange=e=>mutateBattle(()=>z.name=e.target.value);bi.querySelectorAll("[data-pc-start]").forEach(el=>el.onchange=()=>mutateBattle(()=>{s.pcStarts ||= {};s.pcStarts[el.dataset.pcStart]=el.value;}));$("#addLink").onclick=()=>{const target=prompt("Connect to zone id:",s.battlefield.zones.find(q=>q.id!==z.id)?.id||"");if(!target||!s.battlefield.zones.some(q=>q.id===target)||target===z.id)return;const cost=Number(prompt("Move cost:","1"))||1;mutateBattle(()=>s.battlefield.links.push({from:z.id,to:target,cost}));};$("#addEnemy").onclick=()=>mutateBattle(()=>{const used=new Set(s.enemies.map(e=>e.id)),id=unique("enemy",used);s.enemies.push({id,name:"New Enemy",preset:"optimal_killer",zone:z.id,hp:100,maxAp:2,atk:35,def:5,dodge:30,threat:30,abilities:[{id:"strike",name:"Strike",...clone(ABILITY_TEMPLATES["Weak melee"])}]});});$("#addInteraction").onclick=()=>mutateBattle(()=>{s.interactions ||= [];const id=unique("interaction",new Set(s.interactions.map(x=>x.id)));s.interactions.push({id,name:"Interaction",description:"Describe the interaction.",text:"Describe the result.",zone:z.id,ap:1,once:true,effects:[]});});bi.querySelectorAll("[data-edit-enemy]").forEach(b=>b.onclick=()=>renderEnemyEditor(b.dataset.editEnemy));}else bi.innerHTML=`<h3>Battlefield</h3><button id="addZone">+ Zone</button><p class="hint">Select a zone to set starts, enemies, links and interactions.</p>`,$("#addZone").onclick=()=>mutateBattle(()=>{const id=unique("zone",new Set(s.battlefield.zones.map(z=>z.id)));s.battlefield.zones.push({id,name:"New Zone"});});}
  function mutateBattle(fn){checkpoint();fn();render();renderBattlefield();}
  function renderEnemyEditor(id){const s=scenes()[battleSceneId],e=s.enemies.find(x=>x.id===id),bi=$("#battleInspector");bi.innerHTML=`<button id="backZone">← Zone</button><h3>Enemy</h3>${field("ID",e.id,"id")}${field("Name",e.name,"name")}<label class="field"><span>AI preset</span><select id="enemyPreset">${PRESETS.map(p=>`<option ${e.preset===p?"selected":""}>${p}</option>`)}</select></label><div class="row three">${field("HP",e.hp,"hp","number")}${field("AP",e.maxAp,"maxAp","number")}${field("ATK",e.atk,"atk","number")}${field("DEF",e.def,"def","number")}${field("Dodge",e.dodge,"dodge","number")}${field("Threat",e.threat,"threat","number")}</div><div class="section"><h3>Abilities</h3>${(e.abilities||[]).map((a,i)=>`<div class="card"><div class="card-title"><strong>${esc(a.name)}</strong><button data-del-ability="${i}">×</button></div><div class="row three"><input data-ab-name="${i}" value="${esc(a.name)}"><input data-ab-power="${i}" type="number" value="${esc(a.power)}"><input data-ab-range="${i}" type="number" value="${esc(a.maxRange)}"></div></div>`).join("")}<label class="field"><span>Add ability template</span><select id="abilityTemplate">${Object.keys(ABILITY_TEMPLATES).map(k=>`<option>${esc(k)}</option>`)}</select></label><button id="addAbility" class="mini-btn">Add ability</button></div><div class="inline"><button id="duplicateEnemy">Duplicate ×…</button><button id="deleteEnemy" class="danger">Delete</button></div>`;$("#backZone").onclick=renderBattleInspector;bindFields(bi,e);$("#enemyPreset").onchange=x=>mutateBattle(()=>e.preset=x.target.value);bi.querySelectorAll("[data-ab-name]").forEach(x=>x.onchange=()=>mutateBattle(()=>e.abilities[Number(x.dataset.abName)].name=x.value));bi.querySelectorAll("[data-ab-power]").forEach(x=>x.onchange=()=>mutateBattle(()=>e.abilities[Number(x.dataset.abPower)].power=Number(x.value)));bi.querySelectorAll("[data-ab-range]").forEach(x=>x.onchange=()=>mutateBattle(()=>e.abilities[Number(x.dataset.abRange)].maxRange=Number(x.value)));bi.querySelectorAll("[data-del-ability]").forEach(x=>x.onclick=()=>mutateBattle(()=>e.abilities.splice(Number(x.dataset.delAbility),1)));$("#addAbility").onclick=()=>mutateBattle(()=>{const label=$("#abilityTemplate").value,t=clone(ABILITY_TEMPLATES[label]),aid=unique(slug(label),new Set(e.abilities.map(a=>a.id)));e.abilities.push({id:aid,name:label,...t});});$("#duplicateEnemy").onclick=()=>{const n=Math.max(1,Number(prompt("How many copies?","5"))||1);mutateBattle(()=>{const used=new Set(s.enemies.map(x=>x.id));for(let i=0;i<n;i++){const copy=clone(e);copy.id=unique(e.id,used);used.add(copy.id);copy.name=`${e.name} ${i+2}`;s.enemies.push(copy);}});};$("#deleteEnemy").onclick=()=>mutateBattle(()=>s.enemies.splice(s.enemies.indexOf(e),1));}

  function render(){fileLabel.textContent=adventure?(fileHandle?`${adventure.id}.json`:adventure.title):"Untitled";renderGraph();renderInspector();}

  $("#newBtn").onclick=()=>$("#wizardDialog").showModal();$("#createAdventureBtn").onclick=e=>{e.preventDefault();newAdventure($("#wizId").value,$("#wizTitle").value,$("#wizDays").value);$("#wizardDialog").close();};$("#openBtn").onclick=openFile;$("#saveBtn").onclick=saveFile;$("#undoBtn").onclick=undo;$("#redoBtn").onclick=redo;$("#metaBtn").onclick=()=>{selected=null;selectedChoice=null;renderMeta()};$("#stateBtn").onclick=()=>{selected=null;selectedChoice=null;renderState()};$("#validateBtn").onclick=()=>{selected=null;selectedChoice=null;renderValidation()};document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addNode(b.dataset.add));canvas.onclick=()=>{selected=null;selectedChoice=null;render()};$("#jsonBtn").onclick=()=>{if(!adventure)return;$("#jsonText").value=JSON.stringify(adventure,null,2);$("#jsonError").textContent="";$("#jsonDialog").showModal();};$("#applyJsonBtn").onclick=e=>{e.preventDefault();try{const obj=JSON.parse($("#jsonText").value);assertOpenable(obj);checkpoint();adventure=obj;normalizeLayout();selected=null;selectedChoice=null;$("#jsonDialog").close();render();}catch(err){$("#jsonError").textContent=err.message;}};$("#closeBattlefieldBtn").onclick=()=>$("#battlefieldDialog").close();document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="y"){e.preventDefault();redo()}});

  resetHistory(); render();
})();