(function(){
"use strict";
const Core=window.TextGameCore,$=selector=>document.querySelector(selector),app=$("#app"),toolbar=$("#toolbar"),modalRoot=$("#modalRoot"),errorBar=$("#errorBar");
const SLOT_PREFIX="new-trpg-text-game-slot-";
let loadedCharacter=null,loadedAdventure=null,run=null;
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));

function showError(error){errorBar.hidden=false;errorBar.textContent=error instanceof Error?error.message:String(error);window.scrollTo({top:0,behavior:"smooth"})}
function clearError(){errorBar.hidden=true;errorBar.textContent=""}
function attempt(action){try{clearError();action();render()}catch(error){showError(error)}}
function readJsonFile(input,onSuccess){
  const file=input.files?.[0];if(!file)return;
  const reader=new FileReader();reader.onload=()=>{try{const value=JSON.parse(reader.result);onSuccess(value,file.name);clearError();render()}catch(error){showError(new Error(`${file.name}: ${error.message}`));render()}};reader.onerror=()=>{showError(new Error(`Could not read ${file.name}.`));render()};reader.readAsText(file);
}
function slotData(index){try{return JSON.parse(localStorage.getItem(SLOT_PREFIX+index))}catch{return null}}
function slotLabel(data){const current=data?.run?.adventure?.scenes?.[data.run.sceneId];return data?`${data.run.adventure.title} · ${data.run.mainCharacterTemplate.name} · ${current?.title||data.run.sceneId}`:"Empty slot"}
function saveToSlot(index){if(!run)return;const existing=slotData(index);if(existing&&!confirm(`Overwrite save slot ${index}?`))return;localStorage.setItem(SLOT_PREFIX+index,JSON.stringify({savedAt:new Date().toISOString(),run}));closeModal();render()}
function loadSlot(index){const data=slotData(index);if(!data)return;if(data.run.engineVersion!==Core.VERSION)throw new Error(`Save slot ${index} uses an unsupported engine version.`);run=data.run;loadedCharacter=null;loadedAdventure=null;closeModal();render()}
function clearSlot(index){if(slotData(index)&&confirm(`Clear save slot ${index}?`)){localStorage.removeItem(SLOT_PREFIX+index);render()}}
function downloadLog(){
  if(!run)return;const payload={format:"new-trpg-playtest-log",version:1,exportedAt:new Date().toISOString(),runId:run.runId,adventure:{id:run.adventure.id,title:run.adventure.title},mainCharacter:{id:run.mainCharacterTemplate.id,name:run.mainCharacterTemplate.name},status:run.status,sceneId:run.sceneId,world:run.world,events:run.log,currentCombat:run.combat};
  const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${run.adventure.id}-${run.runId}-log.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function closeModal(){modalRoot.innerHTML=""}
function showModal(title,body,actions=[]){modalRoot.innerHTML=`<div class="modal-backdrop" role="presentation"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><h2 id="modalTitle">${esc(title)}</h2>${body}<div class="modal-actions">${actions.map((item,index)=>`<button data-modal-action="${index}" class="${item.className||""}">${esc(item.label)}</button>`).join("")}</div></section></div>`;actions.forEach((item,index)=>$(`[data-modal-action="${index}"]`).onclick=item.action);$(".modal-backdrop").onclick=event=>{if(event.target.classList.contains("modal-backdrop")&&actions.some(x=>x.cancel))closeModal()}}
function saveModal(){showModal("Save game",`<div class="save-grid">${saveCards(false)}</div>`,[{label:"Close",cancel:true,action:closeModal}]);bindSaveCards()}
function logModal(){showModal("Event log",`<div class="combat-log">${run.log.map(entry=>`<p><strong>${entry.sequence}. ${esc(entry.type)}</strong><br>${esc(entry.message)}</p>`).join("")}</div>`,[{label:"Download JSON",className:"primary",action:downloadLog},{label:"Close",cancel:true,action:closeModal}])}
function restart(){if(confirm("Leave this run? Unsaved progress will be lost.")){run=null;loadedCharacter=null;loadedAdventure=null;render()}}

function renderToolbar(){
  if(!run){toolbar.innerHTML="";return}
  toolbar.innerHTML=`<button id="saveGame">Save</button><button id="viewLog">Event log (${run.log.length})</button><button id="downloadLog">Download log</button><button id="leaveRun" class="danger">Leave run</button>`;
  $("#saveGame").onclick=saveModal;$("#viewLog").onclick=logModal;$("#downloadLog").onclick=downloadLog;$("#leaveRun").onclick=restart;
}
function saveCards(includeLoad=true){return[1,2,3].map(index=>{const data=slotData(index);return`<article class="save-card"><strong>Slot ${index}</strong><span>${esc(slotLabel(data))}</span><small>${data?new Date(data.savedAt).toLocaleString():"No saved game"}</small><div class="slot-actions">${includeLoad?`<button data-load-slot="${index}" ${data?"":"disabled"}>Load</button>`:`<button data-save-slot="${index}">Save here</button>`}<button data-clear-slot="${index}" class="quiet" ${data?"":"disabled"}>Clear</button></div></article>`}).join("")}
function bindSaveCards(){document.querySelectorAll("[data-load-slot]").forEach(button=>button.onclick=()=>attempt(()=>loadSlot(Number(button.dataset.loadSlot))));document.querySelectorAll("[data-save-slot]").forEach(button=>button.onclick=()=>attempt(()=>saveToSlot(Number(button.dataset.saveSlot))));document.querySelectorAll("[data-clear-slot]").forEach(button=>button.onclick=()=>clearSlot(Number(button.dataset.clearSlot)))}
function renderSetup(){
  app.innerHTML=`<section class="panel setup"><p class="eyebrow">Strict RAW · Local files · No AI GM</p><h2>Begin an adventure</h2><p class="lede">Choose a reusable main-character file and an adventure file. The adventure supplies the rest of the party, every scripted scene, the single combat encounter, and all possible outcomes.</p><div class="file-grid"><label class="file-card"><strong>Main character JSON</strong><input id="characterFile" type="file" accept="application/json,.json"><p id="characterStatus" class="file-status ${loadedCharacter?"good":""}">${loadedCharacter?`${esc(loadedCharacter.name)} · ${esc(loadedCharacter.role)}`:"No character selected"}</p></label><label class="file-card"><strong>Adventure JSON</strong><input id="adventureFile" type="file" accept="application/json,.json"><p id="adventureStatus" class="file-status ${loadedAdventure?"good":""}">${loadedAdventure?`${esc(loadedAdventure.title)} · ${loadedAdventure.party.length+1} PCs` :"No adventure selected"}</p></label></div><div class="footer-actions"><button id="startAdventure" class="primary" ${loadedCharacter&&loadedAdventure?"":"disabled"}>Start adventure</button></div><hr class="rule"><h3>Manual saves</h3><div class="save-grid">${saveCards(true)}</div></section>`;
  $("#characterFile").onchange=event=>{loadedCharacter=null;readJsonFile(event.target,(value,name)=>{const errors=Core.validateCharacter(value);if(errors.length)throw new Error(`${name}:\n${errors.join("\n")}`);loadedCharacter=value})};
  $("#adventureFile").onchange=event=>{loadedAdventure=null;readJsonFile(event.target,(value,name)=>{const errors=Core.validateAdventure(value);if(errors.length)throw new Error(`${name}:\n${errors.join("\n")}`);loadedAdventure=value})};
  $("#startAdventure").onclick=()=>attempt(()=>{run=Core.createRun(loadedCharacter,loadedAdventure)});bindSaveCards();
}
function modifierText(check){const situational=(check.situationalModifiers||[]).map(item=>`${item.label} ${item.value>=0?"+":""}${item.value}`).join(", ");return`Base ${check.baseTN} · ${check.attributes.map(x=>x.toUpperCase()).join(" + ")} · ${check.skill}${situational?` · ${situational}`:""}`}
function checkChoiceDetails(choice){
  const actors=Core.choiceActors(run,choice);if(choice.actor.mode==="fixed"){const actor=actors[0],check=Core.checkTotal(run,choice,actor.id);return`<div class="mechanics"><strong>${esc(actor.name)}</strong> · ${esc(modifierText(choice.check))}<br>TN <strong>${check.tn}</strong> · Failure may be exchanged for a vaguely disclosed twist.</div>`}
  const totals=actors.map(actor=>`${actor.name} TN ${Core.checkTotal(run,choice,actor.id).tn}`).join(" · ");return`<div class="mechanics">${esc(modifierText(choice.check))}<br><strong>Choose acting character:</strong> ${esc(totals)}</div>`;
}
function renderChoice(choice){return`<article class="choice-card"><div><h3>${esc(choice.label)}</h3>${choice.description?`<p>${esc(choice.description)}</p>`:""}${choice.resolution==="check"?checkChoiceDetails(choice):`<div class="mechanics"><strong>No roll.</strong> ${esc(choice.reason||"The adventure author has established the result.")}</div>`}</div><button data-choice="${esc(choice.id)}" class="${choice.primary?"primary":""}">${choice.resolution==="check"&&choice.actor.mode==="select"?"Choose character":"Choose"}</button></article>`}
function chooseChoice(choice){
  if(choice.resolution!=="check"||choice.actor.mode==="fixed"){const actor=choice.resolution==="check"?Core.choiceActors(run,choice)[0]?.id:null;attempt(()=>Core.resolveChoice(run,choice.id,actor));return}
  const actors=Core.choiceActors(run,choice),body=`<p>${esc(choice.label)}</p><div class="modal-list">${actors.map(actor=>{const detail=Core.checkTotal(run,choice,actor.id);return`<button data-actor="${esc(actor.id)}"><strong>${esc(actor.name)}</strong><br><small>TN ${detail.tn} · ${esc(actor.role)}</small></button>`}).join("")}</div>`;showModal("Who undertakes the action?",body,[{label:"Cancel",cancel:true,action:closeModal}]);document.querySelectorAll("[data-actor]").forEach(button=>button.onclick=()=>{closeModal();attempt(()=>Core.resolveChoice(run,choice.id,button.dataset.actor))})
}
function storyEntryHtml(entry){
  if(entry.type==="scene.entered")return`<div class="scene-break"><span>${esc(entry.message.replace(/^Entered /,"").replace(/\.$/,""))}</span></div>`;
  if(entry.type==="story.dialogue")return`<article class="story-message character-message"><strong>${esc(entry.data.speaker)}</strong><p>${esc(entry.message)}</p></article>`;
  if(entry.type==="story.narration"||entry.type.startsWith("outcome."))return`<article class="story-message gm-message"><strong>GM</strong><p>${esc(entry.message)}</p></article>`;
  if(entry.type==="choice.selected")return`<article class="story-message player-message"><strong>Choice</strong><p>${esc(entry.message)}</p></article>`;
  if(entry.type.startsWith("check.")||entry.type==="clock.progress")return`<article class="story-message rules-message"><strong>Rules</strong><p>${esc(entry.message)}</p></article>`;
  if(entry.type.startsWith("twist."))return`<article class="story-message rules-message"><strong>Twist</strong><p>${esc(entry.message)}</p></article>`;
  return"";
}
function storyStreamHtml(){const entries=run.log.filter(entry=>entry.type==="scene.entered"||entry.type.startsWith("story.")||entry.type==="choice.selected"||entry.type.startsWith("check.")||entry.type.startsWith("outcome.")||entry.type.startsWith("twist.")||entry.type==="clock.progress");return entries.map(storyEntryHtml).join("")||`<p class="empty">The adventure has just begun.</p>`}
function storyStatusHtml(){const days=run.world.quest.remainingDays===null?"":`<div class="status-item"><small>Quest time</small><strong>${run.world.quest.remainingDays-run.world.quest.elapsedDays} day(s) remain</strong></div>`;const clocks=Object.values(run.world.clocks||{}).map(clock=>`<div class="status-item"><small>${esc(clock.label)}</small><strong>${clock.filled}/${clock.size}</strong></div>`).join("");return days||clocks?`<div class="story-status">${days}${clocks}</div>`:""}
function storyShell(decisions){return`<section class="story-screen"><header class="story-heading"><p class="eyebrow">${esc(run.adventure.title)}</p><h2>${esc(Core.scene(run).title)}</h2>${storyStatusHtml()}</header><div class="story-stream">${storyStreamHtml()}</div>${decisions}</section>`}
function renderStory(){const choices=Core.visibleChoices(run),decisions=`<section class="decision-panel"><p class="eyebrow">What happens next?</p><div class="choice-grid">${choices.map(renderChoice).join("")||`<p class="empty">No choices are available in the current state.</p>`}</div></section>`;app.innerHTML=storyShell(decisions);document.querySelectorAll("[data-choice]").forEach(button=>button.onclick=()=>chooseChoice(choices.find(x=>x.id===button.dataset.choice)));document.querySelector(".decision-panel")?.scrollIntoView({block:"end"})}
function renderTwist(){const pending=run.pendingTwist,decision=`<section class="decision-panel twist-decision"><p class="eyebrow">Failed check · Roll ${String(pending.roll).padStart(2,"0")} vs TN ${pending.details.tn}</p><h2>Keep the failure, or accept success with a twist?</h2><div class="fork"><article><h3>Failure</h3><p>${esc(pending.failure.text)}</p><button id="keepFailure">Keep the failed result</button></article><article><h3>Success with a Twist</h3><p class="twist-preview">${esc(pending.twistPreview)}</p><p class="muted">The full complication is revealed after acceptance.</p><button id="acceptTwist" class="primary">Succeed and accept the twist</button></article></div></section>`;app.innerHTML=storyShell(decision);$("#keepFailure").onclick=()=>attempt(()=>Core.resolveTwist(run,false));$("#acceptTwist").onclick=()=>attempt(()=>Core.resolveTwist(run,true));document.querySelector(".twist-decision")?.scrollIntoView({block:"end"})}

function unitCard(unit,enemy=false){const conditions=(unit.conditions||[]).map(x=>x.id||x).join(", "),position=unit.transit?`In transit: ${zoneLabel(unit.transit.from)} → ${zoneLabel(unit.transit.to)} (${unit.transit.progress}/${unit.transit.total})`:zoneLabel(unit.zone);return`<article class="unit ${!enemy&&run.combat.selectedPcId===unit.id?"selected":""} ${unit.hp<=0?"down":""}" ${enemy?"":`data-pc-card="${esc(unit.id)}"`}><h3>${esc(unit.name)}</h3><div class="statline"><span>${enemy?esc(unit.preset.replaceAll("_"," ")):esc(unit.role)}</span><strong>${unit.ap} AP</strong></div><div class="bar ${enemy?"enemy":""}"><i style="width:${clampPercent(unit.hp/unit.maxHp)}%"></i></div><div class="statline"><span>HP ${unit.hp}/${unit.maxHp}</span><span>DEF ${unit.def}</span></div>${enemy?"":`<div class="statline"><span>Stamina ${unit.stamina}/${unit.maxStamina}</span><span>Mana ${unit.mana}/${unit.maxMana}</span><span>IP ${unit.ip}</span></div>`}<small>${esc(position)}${conditions?` · ${esc(conditions)}`:""}</small></article>`}
function clampPercent(value){return Math.max(0,Math.min(100,Math.round(value*100)))}function zoneLabel(id){return run.combat.zones.find(x=>x.id===id)?.name||id}
function zoneHtml(zone){const pcs=run.combat.pcs.filter(x=>x.zone===zone.id),enemies=run.combat.enemies.filter(x=>x.zone===zone.id&&x.alive);return`<article class="zone"><h3>${esc(zone.name)}</h3>${zone.description?`<small>${esc(zone.description)}</small>`:""}${pcs.map(x=>`<span class="occupant pc">◆ ${esc(x.name)} · ${x.hp} HP</span>`).join("")}${enemies.map(x=>`<span class="occupant enemy">◇ ${esc(x.name)} · ${x.hp} HP</span>`).join("")||(!pcs.length?`<span class="occupant">Empty</span>`:"")}</article>`}
function costLabel(ability){const values=[`${ability.ap||0} AP`];if(ability.stamina)values.push(`${ability.stamina} stamina`);if(ability.mana)values.push(`${ability.mana} mana`);return values.join(" · ")}
function selectedPc(){return run.combat.pcs.find(x=>x.id===run.combat.selectedPcId)}
function legalActionButton(ability,pc){let targets=Core.legalAbilityTargets(run.combat,pc,ability);if(ability.kind==="rush")targets=run.combat.enemies.filter(enemy=>enemy.alive&&Core.adjacent(run.combat,pc.zone).some(edge=>edge.cost===1&&edge.zone===enemy.zone));const min=ability.minTargets||1,affordable=pc.ap>=(ability.ap||0)&&pc.stamina>=(ability.stamina||0)&&pc.mana>=(ability.mana||0);return`<button data-ability="${esc(ability.id)}" ${affordable&&targets.length>=min?"":"disabled"}><strong>${esc(ability.name)}</strong><small>${esc(costLabel(ability))} · ${esc(ability.kind)} · Power ${ability.power}</small></button>`}
function actionPanel(){
  const combat=run.combat;if(combat.phase!=="pc")return`<section class="panel"><h3>Enemy phase</h3><p>The deterministic controller is resolving enemy actions. Player decisions pause here when a reaction is available.</p></section>`;
  const pc=selectedPc();if(!pc)return`<section class="panel"><h3>Choose the next PC</h3><p>Player characters may act in any order. Select a conscious character who has not acted.</p></section>`;
  if(pc.acted||pc.hp<=0)return`<section class="panel"><h3>${esc(pc.name)} cannot act</h3><p>Choose another character.</p></section>`;
  if(pc.rallyDue)return`<section class="panel critical-panel"><p class="eyebrow">Start of turn</p><h3>Will ${esc(pc.name)} sustain Rallied?</h3><p>Spend 1 AP to sustain every original target of the invocation, or let the condition end.</p><div class="footer-actions"><button id="dropRallied">Let it end</button><button id="sustainRallied" class="primary" ${pc.ap<1?"disabled":""}>Spend 1 AP</button></div></section>`;
  if(pc.transit)return`<section class="panel"><p class="eyebrow">In transit</p><h3>${esc(pc.name)} is crossing toward ${esc(zoneLabel(pc.transit.to))}</h3><p>${pc.transit.progress}/${pc.transit.total} Moves completed. A character in transit cannot use ordinary abilities or reactions.</p><div class="action-grid"><button id="continueTransit" ${pc.ap<1?"disabled":""}>Continue crossing</button><button id="abandonTransit">Abandon and return to ${esc(zoneLabel(pc.transit.from))}</button></div><div class="footer-actions"><button id="endTurn" class="primary">End ${esc(pc.name)}'s turn</button></div></section>`;
  if(pc.conditions.some(x=>(x.id||x)==="Incapacitated"))return`<section class="panel"><h3>${esc(pc.name)} is Incapacitated</h3><p>Their single AP may only be spent on Recover.</p><div class="action-grid"><button id="recoverAction">Recover</button><button id="endTurn">End turn</button></div></section>`;
  const interactions=Core.availableInteractions(combat,pc);return`<section class="panel"><p class="eyebrow">Active character</p><h3>${esc(pc.name)} · ${pc.ap} AP</h3><div class="action-grid">${pc.abilities.map(ability=>legalActionButton(ability,pc)).join("")}<button id="moveAction" ${pc.ap<1?"disabled":""}><strong>Move</strong><small>Connection cost in AP</small></button><button id="consumableAction" ${pc.ap<1||pc.ip<1?"disabled":""}><strong>Use Consumable</strong><small>1 AP · 1 Inventory Point</small></button><button id="recoverAction" ${pc.ap<1?"disabled":""}><strong>Recover</strong><small>1 AP · Range 0</small></button>${interactions.length?`<button id="interactAction"><strong>Interact</strong><small>${interactions.length} authored option${interactions.length===1?"":"s"} here</small></button>`:""}<button id="prepareAction"><strong>Prepare Action</strong><small>Pay only when triggered</small></button></div><div class="footer-actions"><button id="endTurn" class="primary">End ${esc(pc.name)}'s turn</button></div></section>`;
}
function criticalPanel(){const combat=run.combat;if(combat.round!==combat.nextCriticalRound||combat.criticalUsed)return"";return`<section class="panel critical-panel"><p class="eyebrow">Critical Round</p><h3>The party's Critical is available</h3><p>Spend it on a Critical Attack, an Invincibility Frame, or Critical Recovery before this round ends.</p><button id="useCritical">Choose Critical benefit</button></section>`}
function pendingPanel(){
  const pending=run.combat.pending;if(!pending)return"";
  if(pending.type==="prepared"){const pc=run.combat.pcs.find(x=>x.id===pending.pcId),enemy=run.combat.enemies.find(x=>x.id===pending.enemyId),ability=pc.abilities.find(x=>x.id===pending.abilityId);return`<section class="panel pending"><p class="eyebrow">Prepared action triggered</p><h3>${esc(pc.name)} may use ${esc(ability.name)}</h3><p>${esc(enemy.name)} has met the declared trigger. Pay ${esc(costLabel(ability))} and resolve the attack?</p><div class="footer-actions"><button id="skipPrepared">Do not use it</button><button id="usePrepared" class="primary">Use ${esc(ability.name)}</button></div></section>`}
  const source=run.combat.enemies.find(x=>x.id===pending.sourceId),target=run.combat.pcs.find(x=>x.id===pending.targetId),options=Core.reactionOptions(run.combat,pending);const critical=run.combat.round===run.combat.nextCriticalRound&&!run.combat.criticalUsed;return`<section class="panel pending"><p class="eyebrow">Reaction</p><h3>${esc(source.name)} uses ${esc(pending.attack.name)} against ${esc(target.name)}</h3><p>${pending.attack.power} ATK. Choose how the party responds.</p><div class="action-grid">${options.map(option=>`<button data-reaction="${esc(option.id)}">${esc(option.label)}</button>`).join("")}${critical?`<button id="criticalInvincibility"><strong>Invincibility Frame</strong><small>Spend the party's Critical; prevent this effect and all later hostile effects this round.</small></button>`:""}</div></section>`;
}
function renderCombat(){const combat=run.combat;app.innerHTML=`<div class="combat-layout"><div class="combat-main"><section class="panel battle-head"><div><p class="eyebrow">${esc(run.adventure.title)}</p><h2>${esc(combat.name)}</h2></div><span class="round-badge">Round ${combat.round} · ${combat.phase.toUpperCase()} phase</span></section>${pendingPanel()}${criticalPanel()}<section class="zone-grid">${combat.zones.map(zoneHtml).join("")}</section><section class="card-grid">${combat.pcs.map(pc=>unitCard(pc)).join("")}</section>${combat.pending?"":actionPanel()}</div><aside class="panel history"><h3>Opposition</h3><div class="card-grid">${combat.enemies.filter(x=>x.alive).map(enemy=>unitCard(enemy,true)).join("")}</div><h3>Combat log</h3><div class="combat-log">${combat.log.slice(-80).map(entry=>`<p class="${esc(entry.type)}">${esc(entry.message)}</p>`).join("")}</div></aside></div>`;bindCombat()}
function bindCombat(){
  const combat=run.combat;document.querySelectorAll("[data-pc-card]").forEach(card=>card.onclick=()=>{if(combat.phase==="pc"&&!combat.pending)attempt(()=>Core.beginPcTurn(run,card.dataset.pcCard))});
  if(combat.pending?.type==="prepared"){$("#skipPrepared").onclick=()=>attempt(()=>Core.resolvePrepared(run,false));$("#usePrepared").onclick=()=>preparedTargetsModal(combat.pending)}
  document.querySelectorAll("[data-reaction]").forEach(button=>button.onclick=()=>attempt(()=>Core.resolveReaction(run,button.dataset.reaction)));
  if($("#criticalInvincibility"))$("#criticalInvincibility").onclick=()=>attempt(()=>{Core.useCritical(run,"invincibility",combat.pending.targetId);Core.resolveReaction(run,"take")});
  if(combat.pending)return;
  if($("#useCritical"))$("#useCritical").onclick=criticalModal;
  const pc=selectedPc();if(!pc)return;document.querySelectorAll("[data-ability]").forEach(button=>button.onclick=()=>abilityModal(pc,pc.abilities.find(x=>x.id===button.dataset.ability)));
  if($("#sustainRallied"))$("#sustainRallied").onclick=()=>attempt(()=>Core.resolveRallySustain(run,pc.id,true));if($("#dropRallied"))$("#dropRallied").onclick=()=>attempt(()=>Core.resolveRallySustain(run,pc.id,false));
  if($("#continueTransit"))$("#continueTransit").onclick=()=>attempt(()=>Core.movePc(run,pc.id,pc.transit.to));if($("#abandonTransit"))$("#abandonTransit").onclick=()=>attempt(()=>Core.abandonTransit(run,pc.id));
  if($("#moveAction"))$("#moveAction").onclick=()=>moveModal(pc);if($("#consumableAction"))$("#consumableAction").onclick=()=>consumableModal(pc);if($("#recoverAction"))$("#recoverAction").onclick=()=>recoverModal(pc);if($("#interactAction"))$("#interactAction").onclick=()=>interactionModal(pc);if($("#prepareAction"))$("#prepareAction").onclick=()=>prepareModal(pc);if($("#endTurn"))$("#endTurn").onclick=()=>attempt(()=>Core.endPcTurn(run,pc.id));
}
function moveModal(pc){const moves=Core.adjacent(run.combat,pc.zone);showModal("Move",`<p>${esc(pc.name)} is in ${esc(zoneLabel(pc.zone))}. Long connections preserve progress across rounds.</p><div class="modal-list">${moves.map(move=>`<button data-move="${esc(move.zone)}">${esc(zoneLabel(move.zone))}<br><small>${move.cost} Move${move.cost===1?"":"s"}</small></button>`).join("")}</div>`,[{label:"Cancel",cancel:true,action:closeModal}]);document.querySelectorAll("[data-move]").forEach(button=>button.onclick=()=>{closeModal();attempt(()=>Core.movePc(run,pc.id,button.dataset.move))})}
function abilityModal(pc,ability){
  let candidates=Core.legalAbilityTargets(run.combat,pc,ability);if(ability.kind==="rush")candidates=run.combat.enemies.filter(enemy=>enemy.alive&&Core.adjacent(run.combat,pc.zone).some(edge=>edge.cost===1&&edge.zone===enemy.zone));
  const min=ability.minTargets||1,max=ability.maxTargets||1;if(max>1)return multipleTargetsModal(pc,ability,candidates,min,max);
  showModal(ability.name,`<p>${esc(costLabel(ability))}. Choose a target.</p><div class="modal-list">${candidates.map(target=>`<button data-target="${esc(target.id)}"><strong>${esc(target.name)}</strong><br><small>${target.hp}/${target.maxHp} HP · ${esc(zoneLabel(target.zone))}</small></button>`).join("")}</div>`,[{label:"Cancel",cancel:true,action:closeModal}]);document.querySelectorAll("[data-target]").forEach(button=>button.onclick=()=>{const target=candidates.find(x=>x.id===button.dataset.target);if(ability.kind==="push"){pushModal(pc,ability,target);return}closeModal();attempt(()=>Core.performPcAbility(run,pc.id,ability.id,[target.id],ability.kind==="rush"?{moveTo:target.zone}:{}))})
}
function multipleTargetsModal(pc,ability,candidates,min,max){let selected=[];function draw(){showModal(ability.name,`<p>Choose ${min}–${max} targets.</p><div class="modal-list">${candidates.map(target=>`<button class="target-toggle ${selected.includes(target.id)?"selected":""}" data-toggle-target="${esc(target.id)}">${selected.includes(target.id)?"✓ ":""}${esc(target.name)} · ${target.hp}/${target.maxHp} HP</button>`).join("")}</div>`,[{label:"Cancel",cancel:true,action:closeModal},{label:`Confirm ${selected.length}`,className:"primary",action:()=>{if(selected.length<min)return;closeModal();attempt(()=>Core.performPcAbility(run,pc.id,ability.id,selected))}}]);document.querySelectorAll("[data-toggle-target]").forEach(button=>button.onclick=()=>{const id=button.dataset.toggleTarget;selected=selected.includes(id)?selected.filter(x=>x!==id):selected.length<max?[...selected,id]:selected;draw()})}draw()}
function pushModal(pc,ability,target){const destinations=Core.adjacent(run.combat,target.zone).filter(x=>x.cost===1);showModal("Forced movement",`<p>Choose where ${esc(target.name)} is pushed if the attack deals damage.</p><div class="modal-list"><button data-push="">Do not push</button>${destinations.map(x=>`<button data-push="${esc(x.zone)}">${esc(zoneLabel(x.zone))}</button>`).join("")}</div>`,[{label:"Cancel",cancel:true,action:closeModal}]);document.querySelectorAll("[data-push]").forEach(button=>button.onclick=()=>{closeModal();attempt(()=>Core.performPcAbility(run,pc.id,ability.id,[target.id],{destination:button.dataset.push||null}))})}
function consumableModal(pc){const options=[{id:"hp",label:"Restore 50 HP",show:pc.hp<pc.maxHp},{id:"stamina",label:"Restore 5 stamina",show:pc.stamina<pc.maxStamina},{id:"mana",label:"Restore 6 mana",show:pc.mana<pc.maxMana}].filter(x=>x.show);showModal("Use Consumable",`<p>Spend 1 AP and 1 Inventory Point.</p><div class="modal-list">${options.map(x=>`<button data-consumable="${x.id}">${x.label}</button>`).join("")}</div>`,[{label:"Cancel",cancel:true,action:closeModal}]);document.querySelectorAll("[data-consumable]").forEach(button=>button.onclick=()=>{closeModal();attempt(()=>Core.useConsumable(run,pc.id,button.dataset.consumable))})}
function recoverModal(pc){const options=run.combat.pcs.filter(x=>x.zone===pc.zone).flatMap(target=>(target.conditions||[]).map(condition=>({target,id:condition.id||condition})));showModal("Recover",`<p>Remove one condition from ${esc(zoneLabel(pc.zone))}.</p><div class="modal-list">${options.map((x,index)=>`<button data-recover="${index}">${esc(x.target.name)} · ${esc(x.id)}</button>`).join("")||`<p class="empty">No condition can be Recovered here.</p>`}</div>`,[{label:"Cancel",cancel:true,action:closeModal}]);document.querySelectorAll("[data-recover]").forEach(button=>button.onclick=()=>{const option=options[Number(button.dataset.recover)];closeModal();attempt(()=>Core.recover(run,pc.id,option.target.id,option.id))})}
function interactionModal(pc){const options=Core.availableInteractions(run.combat,pc);showModal("Interact",`<p>Choose a meaningful interaction in ${esc(zoneLabel(pc.zone))}.</p><div class="modal-list">${options.map(option=>`<button data-interaction="${esc(option.id)}"><strong>${esc(option.name)}</strong><br><small>${esc(option.description||option.text)} · ${option.ap??1} AP</small></button>`).join("")}</div>`,[{label:"Cancel",cancel:true,action:closeModal}]);document.querySelectorAll("[data-interaction]").forEach(button=>button.onclick=()=>{closeModal();attempt(()=>Core.performInteraction(run,pc.id,button.dataset.interaction))})}
function prepareModal(pc){const abilities=pc.abilities.filter(x=>["attack","multi","push","persistent","rush"].includes(x.kind)&&pc.ap>=(x.ap||0)&&pc.stamina>=(x.stamina||0)&&pc.mana>=(x.mana||0));showModal("Prepare an action",`<p>Choose an ability and an observable trigger. Costs are paid only if it triggers.</p><div class="modal-list">${abilities.flatMap(ability=>[{ability,trigger:"enemy-enters-range",label:`${ability.name} — enemy enters range`},{ability,trigger:"enemy-attacks-ally",label:`${ability.name} — enemy attacks an ally in my zone`}]).map((x,index)=>`<button data-prepare="${index}">${esc(x.label)}</button>`).join("")}</div>`,[{label:"Cancel",cancel:true,action:closeModal}]);const options=abilities.flatMap(ability=>[{ability,trigger:"enemy-enters-range"},{ability,trigger:"enemy-attacks-ally"}]);document.querySelectorAll("[data-prepare]").forEach(button=>button.onclick=()=>{const option=options[Number(button.dataset.prepare)];closeModal();attempt(()=>Core.prepare(run,pc.id,option.ability.id,option.trigger))})}
function preparedTargetsModal(pending){const pc=run.combat.pcs.find(x=>x.id===pending.pcId),ability=pc.abilities.find(x=>x.id===pending.abilityId),trigger=run.combat.enemies.find(x=>x.id===pending.enemyId),candidates=Core.legalAbilityTargets(run.combat,pc,ability),min=ability.minTargets||1,max=ability.maxTargets||1;if(max===1){attempt(()=>Core.resolvePrepared(run,true,[trigger.id]));return}let selected=[trigger.id];function draw(){showModal(`Prepared ${ability.name}`,`<p>Choose ${min}–${max} targets. The triggering enemy must remain selected.</p><div class="modal-list">${candidates.map(target=>`<button class="target-toggle ${selected.includes(target.id)?"selected":""}" data-prepared-target="${esc(target.id)}" ${target.id===trigger.id?"disabled":""}>${selected.includes(target.id)?"✓ ":""}${esc(target.name)} · ${target.hp}/${target.maxHp} HP</button>`).join("")}</div>`,[{label:"Cancel",cancel:true,action:closeModal},{label:`Use on ${selected.length}`,className:"primary",action:()=>{if(selected.length<min)return;closeModal();attempt(()=>Core.resolvePrepared(run,true,selected))}}]);document.querySelectorAll("[data-prepared-target]").forEach(button=>button.onclick=()=>{const id=button.dataset.preparedTarget;selected=selected.includes(id)?selected.filter(x=>x!==id):selected.length<max?[...selected,id]:selected;draw()})}draw()}
function criticalModal(){const pcs=run.combat.pcs;showModal("Spend the party's Critical",`<div class="modal-list"><button id="criticalAttack">Critical Attack</button><button id="criticalFrame">Invincibility Frame</button><button id="criticalRecovery">Critical Recovery</button></div>`,[{label:"Cancel",cancel:true,action:closeModal}]);$("#criticalAttack").onclick=()=>criticalTargetModal("attack",pcs.filter(x=>x.hp>0));$("#criticalFrame").onclick=()=>criticalTargetModal("invincibility",pcs.filter(x=>x.hp>0));$("#criticalRecovery").onclick=()=>criticalTargetModal("recovery",pcs)}
function criticalTargetModal(kind,pcs){showModal(kind==="attack"?"Critical Attack":kind==="recovery"?"Critical Recovery":"Invincibility Frame",`<div class="modal-list">${pcs.map(pc=>`<button data-critical-pc="${esc(pc.id)}">${esc(pc.name)} · ${pc.hp}/${pc.maxHp} HP</button>`).join("")}</div>`,[{label:"Cancel",cancel:true,action:closeModal}]);document.querySelectorAll("[data-critical-pc]").forEach(button=>button.onclick=()=>{const pcId=button.dataset.criticalPc;if(kind!=="attack"){closeModal();attempt(()=>Core.useCritical(run,kind,pcId));return}showModal("Critical Attack attribute",`<p>Choose the attribute added twice to Critical ATK.</p><div class="modal-list">${["dex","agi","str","int"].map(attribute=>`<button data-critical-attribute="${attribute}">${attribute.toUpperCase()}</button>`).join("")}</div>`,[{label:"Cancel",cancel:true,action:closeModal}]);document.querySelectorAll("[data-critical-attribute]").forEach(attributeButton=>attributeButton.onclick=()=>{closeModal();attempt(()=>Core.useCritical(run,"attack",pcId,attributeButton.dataset.criticalAttribute))})})}

function renderEnding(){const current=Core.scene(run),outcome=run.status,ending=run.ending||{title:current?.title||run.adventure.title,text:typeof current?.text==="string"?current.text:run.log.at(-1)?.message||""};app.innerHTML=`<section class="panel ending ${outcome}"><p class="eyebrow">Adventure complete</p><div class="outcome">${esc(outcome.toUpperCase())}</div><h2>${esc(ending.title)}</h2><p class="lede">${esc(ending.text)}</p><div class="footer-actions"><button id="endingLog">View event log</button><button id="endingDownload" class="primary">Download playtest log</button><button id="endingLeave">Return to start</button></div></section>`;$("#endingLog").onclick=logModal;$("#endingDownload").onclick=downloadLog;$("#endingLeave").onclick=restart}
function render(){renderToolbar();if(!run)renderSetup();else if(run.status!=="playing")renderEnding();else if(run.combat)renderCombat();else if(run.pendingTwist)renderTwist();else renderStory();app.focus({preventScroll:true})}
render();
})();
